apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: online-boutique
  namespace: online-boutique
spec:
  exporter:
    endpoint: http://otel-collector.monitoring.svc.cluster.local:4318

  propagators:
    - tracecontext
    - baggage

  sampler:
    type: parentbased_traceidratio
    argument: "1"

  java:
    env:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf

  dotnet:
    env:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf