apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: cartservice-pod-kill
  namespace: online-boutique
spec:
  schedule: "*/2 * * * *"

  type: PodChaos

  podChaos:
    action: pod-kill
    mode: one

    selector:
      namespaces:
        - online-boutique

      labelSelectors:
        app: cartservice