# 1. Prometheus
prometheus:
  prometheusSpec:
    retention: 2d
    retentionSize: "3GB"

    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi


# 2. Grafana
grafana:
  plugins: []
  enabled: true
  adminPassword: "admin"

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 10
    failureThreshold: 10

  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 10


# 3. Tối ưu cấu hình Alertmanager
alertmanager:
  enabled: true

  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

  config:
    global:
      resolve_timeout: 5m

    route:
      group_by:
        - alertname
        - namespace
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h

      # Receiver mặc định
      receiver: telegram

      routes:
        # Watchdog không cần gửi Telegram
        - matchers:
            - alertname = "Watchdog"
          receiver: "null"

    receivers:
      # Receiver dùng để bỏ qua alert
      - name: "null"

      # Receiver gửi Telegram
      - name: telegram
        telegram_configs:
          - bot_token: "8692885374:AAGh5yUVSOwmrNZe7BDxGbgHwxJOulF6Uy0"
            chat_id: 8319467679
            send_resolved: true


# 4. Prometheus Operator
prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi


# 5. Node Exporter
nodeExporter:
  enabled: true


# 6. kube-state-metrics
kubeStateMetrics:
  enabled: true

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false