apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-cart-servicemonitor
  namespace: online-boutique
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - online-boutique
  selector:
    matchLabels:
      app: redis-cart
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s