# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
  namespace: online-boutique
spec:
  replicas: 2 # Duy trì ít nhất 2 replicas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%        # Tạo thêm tối đa 25% Pods phiên bản mới trước khi xóa Pods cũ
      maxUnavailable: 0
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      serviceAccountName: paymentservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: paymentservice
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          initialDelaySeconds: 5  # Chờ 5s cho ứng dụng khởi động trước khi bắt đầu check readiness
          periodSeconds: 5        # Tần suất kiểm tra mỗi 5 giây
          timeoutSeconds: 2       # Thời gian timeout cho mỗi lần check
          failureThreshold: 3     # Thất bại 3 lần liên tiếp sẽ đánh dấu Pod chưa sẵn sàng nhận traffic
          grpc:
            port: 50051
        livenessProbe:
          initialDelaySeconds: 15 # Chờ 15s trước khi bật tính năng kiểm tra sống/chết của container
          periodSeconds: 10       # Kiểm tra mỗi 10 giây
          timeoutSeconds: 2       # Thời gian timeout cho mỗi lần check
          failureThreshold: 3     # Thất bại 3 lần liên tiếp sẽ tiến hành restart lại container
          grpc:
            port: 50051
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentservice
