name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-southeast-1
  EKS_CLUSTER: observability-demo-cluster

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        service:
          - frontend
          - cartservice
          - checkoutservice
          - productcatalogservice
          - shippingservice
          - paymentservice
          - emailservice
          - recommendationservice
          - currencyservice
          - adservice
          - loadgenerator

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Debug repository
        run: |
          echo "Current directory:"
          pwd

          echo "Dockerfiles:"
          find src -name Dockerfile -print

      - name: Build and push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SERVICE: ${{ matrix.service }}
          TAG: ${{ github.sha }}
        run: |
          set -euxo pipefail

          IMAGE="$REGISTRY/online-boutique/$SERVICE:$TAG"

          echo "================================"
          echo "Service: $SERVICE"
          echo "Image:   $IMAGE"
          echo "================================"

          if [ "$SERVICE" = "cartservice" ]; then

            echo "Cartservice special build"

            test -f ./src/cartservice/src/Dockerfile

            docker build \
              -f ./src/cartservice/src/Dockerfile \
              -t "$IMAGE" \
              ./src/cartservice/src

          else

            echo "Normal service build"

            test -f "./src/$SERVICE/Dockerfile"

            docker build \
              -t "$IMAGE" \
              "./src/$SERVICE"

          fi

          echo "Pushing $IMAGE"

          docker push "$IMAGE"